export default function getAllProducts() {
  return [
    {
      id: "PMM-BS",
      slug: "Paket-Mini-Magic",
      name: "Paket Mini Magic",
      category: `Badut Sulap`,
      categorySlug: "badut-sulap",
      price: 500_000,
      stock: 20,
      imageUrl: "/assets/images/badut1.jpg",
      description: `Badut dengan trik sulap sederhana yang interaktif, cocok untuk acara kecil atau kegiatan santai. Durasi 30 menit, dengan alat sulap ramah anak yang menghibur.`,
    },
    {
      id: "PMF-BS",
      slug: "Paket-Magical-Fun",
      name: "Paket Magical Fun",
      category: `Badut Sulap`,
      categorySlug: "badut-sulap",
      price: 600_000,
      stock: 18,
      imageUrl: `/assets/images/badut2.jpg`,
      description: `Hiburan badut dengan kombinasi sulap klasik dan permainan interaktif. Durasi 1 jam, dilengkapi sesi foto bersama serta hadiah kecil untuk penonton yang berpartisipasi.`,
    },
    {
      id: "PMS-BS",
      slug: "Paket-Mystichal-Show",
      name: "Paket Mystichal Show",
      category: `Badut Sulap`,
      categorySlug: "badut-sulap",
      price: 700_000,
      stock: 100,
      imageUrl: `/assets/images/badut3.jpg`,
      description: `Pertunjukan sulap premium dengan trik-trik memukau yang melibatkan audiens. Durasi 1,5 jam, cocok untuk acara formal seperti pesta kantor atau ulang tahun spesial.`,
    },
    {
      id: "PEP-BS",
      slug: "Paket-Enchanted-Performance",
      name: "Paket Enchanted Performance",
      category: `Badut Sulap`,
      categorySlug: "badut-sulap",
      price: 800_000,
      stock: 0,
      imageUrl: `/assets/images/badut4.jpg`,
      description: `Pertunjukan badut sulap eksklusif dengan efek visual tambahan, seperti api kecil (aman) dan sulap kartu profesional. Durasi 2 jam, ideal untuk acara besar dengan tema magis.`,
    },
    {
      id: "PFM-BA",
      slug: "Paket-Fun-Moves",
      name: "Paket Fun Moves",
      category: `Badut Atraksi`,
      categorySlug: "badut-atraksi",
      price: 750_000,
      stock: 11,
      imageUrl: `/assets/images/badut5.jpg`,
      description: `Badut dengan gerakan lucu, permainan balon, dan aktivitas kecil seperti game ringan. Durasi 30 menit, cocok untuk acara sederhana dan budget-friendly.`,
    },
    {
      id: "PHJ-BA",
      slug: "Paket-Happy-Jumpers",
      name: "Paket Happy Jumpers",
      category: `Badut Atraksi`,
      categorySlug: "badut-atraksi",
      price: 950_000,
      stock: 100,
      imageUrl: `/assets/images/badut6.jpg`,
      description: `Badut atraksi dengan trik balon kreatif, gerakan akrobat ringan, serta permainan interaktif. Durasi 1 jam, menghadirkan suasana penuh tawa dan keseruan.`,
    },
    {
      id: "PCD-BA",
      slug: "Paket-Circus-Delight",
      name: "Paket Circus Delight",
      category: `Badut Atraksi`,
      categorySlug: "badut-atraksi",
      price: 1_050_000,
      stock: 23,
      imageUrl: `/assets/images/badut7.jpg`,
      description: `Aksi badut atraksi dengan tambahan juggling, permainan bola, dan trik sepeda kecil. Durasi 1,5 jam, cocok untuk acara meriah dengan penonton anak-anak maupun keluarga.`,
    },
    {
      id: "PEC-BA",
      slug: "Paket-Extreme-Clowning",
      name: "Paket Extreme Clowning",
      category: `Badut Atraksi`,
      categorySlug: "badut-atraksi",
      price: 1_200_000,
      stock: 0,
      imageUrl: `/assets/images/badut8.jpg`,
      description: `Pertunjukan atraksi spektakuler oleh badut profesional, termasuk aksi unicycle (sepeda roda satu) dan juggling tingkat tinggi. Durasi 2 jam, pas untuk acara besar yang ingin meninggalkan kesan mendalam.`,
    },

    {
      id: "PHC-BK",
      slug: "Paket-Happy-Clown",
      name: "Paket Happy Clown",
      category: `Badut Klasik`,
      categorySlug: "badut-klasik",
      price: 300_000,
      stock: 33,
      imageUrl: `/assets/images/badut9.jpg`,
      description: `Hadirkan keceriaan di acara Anda dengan badut ceria kami! Paket ini mencakup pertunjukan badut klasik dengan kostum warna-warni, permainan interaktif, dan kreasi balon untuk anak-anak. Cocok untuk ulang tahun atau acara keluarga.`,
    },
    {
      id: "PCF-BK",
      slug: "Paket-Classic-Fun",
      name: "Paket Classic Fun",
      category: `Badut Klasik`,
      categorySlug: "badut-klasik",
      price: 430_000,
      stock: 111,
      imageUrl: `/assets/images/badut10.jpg`,
      description: `Nikmati keseruan badut klasik yang penuh tawa! Paket ini menawarkan pertunjukan badut dengan trik sulap sederhana, cerita lucu, dan gerakan menghibur untuk segala usia. Pilihan ideal untuk acara santai dan menyenangkan.`,
    },
    {
      id: "PEP-BK",
      slug: "Paket-Energetic-Performer",
      name: "Paket Energetic Performer",
      category: `Badut Klasik`,
      categorySlug: "badut-klasik",
      price: 550_000,
      stock: 100,
      imageUrl: `/assets/images/badut11.jpg`,
      description: `Rasakan energi luar biasa dari badut kami! Paket ini menghadirkan atraksi juggling, tarian lucu, serta tantangan interaktif yang melibatkan penonton. Cocok untuk acara di dalam maupun luar ruangan.`,
    },
    {
      id: "PSC-BK",
      slug: "Paket-Surprise-Clown",
      name: "Paket Surprise Clown",
      category: `Badut Klasik`,
      categorySlug: "badut-klasik",
      price: 700_000,
      stock: 0,
      imageUrl: `/assets/images/badut12.jpg`,
      description: `Lengkapi acara Anda dengan badut yang penuh kejutan! Paket ini mencakup kemunculan badut secara tiba-tiba, aksi teatrikal, serta pengantaran hadiah kepada tamu istimewa. Sangat pas untuk acara spesial atau perayaan unik.`,
    },
  ];
}
